language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- lts/*
env:
  global:
  - secure: aIFnWmyQMAYSAGp3Dy3kQW6e1jgl2amPKWmCWY9+Wqz1NQS882dPcbJoo3dmH3jaU960o3gBeQQSQOIuKm+4cYA27XBGe0hpOkCZVFjlnY8tEHyEmvn8MCU8b493TkKINVrsgEZDy3lJhSuLVn6lRfrL+SOZpJk0Rlf/IThSl+NrOLsYyf9DgS/13cPLpU8NWxcAPWXJ6wihWJnIJuWpMA8f5cMai0EXQY7gp2SfPj+hshpbAtQ45qKGDzRrq/6/daUbH7Ac1Q7tVGwmn/Pr7vsQvqNtDfDRgFEuUtqXhtMg4QLFawWhC4OGG1kI7If9S5m43wi8yI7uYfVxLdkxWqgLu24LrhLqRraOHN1PdCwfzkgklTN3WPp14t+G5Rq/VbCW4C1BT3qTneTwWJQQm/bvK+A4OILh9bdz1vmyu4+DZvfmZSafF8KE0xovg4er3baiftK0LDd7Vby+7nb7r8d5UdTAqLQvQo8a4PxmKdhskvXyt4tqJW6OMDbdZBuVH3AQNXR3o8okX5TlGqwwtKWOW6diokZooFw6FjMgdkt8bAJJZ8YG7kG11iwkmwI9k8EB9D16lzqxTwxkl5qbXYOJtgveLqRDXR+SU8j3DDvXMK75PEVetQMcPjo2lc50ybmtjCA7Lldkh2X8NLrMPziaY33wdfRmwupofBx5DMo=
  - secure: Y9UPGauqeCr5/joT2mmQ1qc+KdeEcpH/J0utUFfyTm7+tCgH5zulByIuP27lmlh20A5H4jl+RSxIQKA4uh9t1LBYXHnqQSuQvLv+6aR9nl0xctuzL/xl/0jIrX8JDPNXzhZELEVqtIOhwFLHUggWAd3cehETCxvnwObcK0vJtR0RlWO9lAc0fYju+qPf5sZizeIMFPKXwVZljAyRLmXbno619WZumQ9KA1/HV5HSali3OROx2lshhxKxf1ITbNTUl5iSGrxwhCkuEQxIOTE4jyZgeuklbAOpJArwbAEhGXJ+JZR5kKin9A0m83epceF4qQkaphRpuoXIu+0o+uCsinYj8O1xmSnI1tbPhbQ6Nc/rKhVLiq4WBRmGf8Fd6Mcm+ufGAsFfbrZ/Wjud3+vH5ijn28FV72vbs6LEdiw+QUNRicDzNo6yS4IhWyXDi9+ooLs8oDAiWFHpVQglcTDbTItZTUR7bCO/sC0GxcXD5FMcHbdPpvqK5pFyjq2kh8OO1pVYdiXdvUFqiCn2bXB5Ih/npTkovDeCN/wSQtH2tPnEYjt0iga88VnDYaLlEXLYl+DfgH2QM03WSJsiE6PXBkf/uB+ZH5og1Rx1daE4H0thvO6WLhBpHo8VhTbydnQFvIu/TM3aW44dUULB8zAbOs6ol7tYnZEycx4MyT0AjnE=
