language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- lts/*
env:
  global:
  - secure: Kj/+GT+uAH9h0gJvlgEEQhzqgaei+0upeVgXM46o/97PZBz61oIGuj3avaTYlijH8IvipqziBTJyh7VK2oRzXRp5GXfpEBVvr5C/bSeAMuRPtoPED0b8od3iJ9BcW8bijA5I9ahCi31Ow4rLXKJU9wb1/9ZAnmw/nmHCKoTnBlYnzeWuggELeWtTtK5evDKKM2s/NHqEcA6xN5dwBvukiIK1q4h+leWooHu8s12PIKisSiomMu5bTg/8rgovCulLbb3xjdcsrKK/ADVffYvULC5NCpJch93qH9vnLGM2Ht+BpjoG6c85UZwUgxlrX6qwRYatGb+k6YUyCuLpMQxLCiJ961GE4RTYtYn0EDWkT4dxfAlwmPkK9I++mj9rDx/X/gKm9CndVN0ZuDWQJqvYL4pXDuNF3rRiBN6tFePBE3JLAe0ivxSDRjaKeZ430MkyfeIlu5L/rio0bvsym+gY4AxNEwbllDAm46Zap9MTYFs4gIdX/qmG3JSOgeQY6kvRwXaTQlpEqiBL9uxvbZBGFZ5lPUNDhIbnK8cllf3pq89E1BWTkPo50efnglKRyiftze+ihkP7aKbeIm4FORNilRwxrkQOdr3NjWhvKY3+PJSdPVVBsIyE9Rt48WTn7YIOPbkW55JkNJqR+CpjXR+kmem5i0qjnKcX0iy1P6Ht0HE=